name: Run AWS ECS Task
description: Runs a task in AWS ECS
author: Icalia Labs

branding:
  icon: activity
  color: red

inputs:
  cluster:
    description: The AWS ECS cluster where we should run the task
    required: true
  name:
    description: The name of the AWS ECS Task
    required: true
  template:
    description: The template used to run the task (i.e. --cli-input-json | --cli-input-yaml)
    required: false
  definition-template:
    description: The path to the AWS ECS Task Definition template to use
    required: false
  container-images:
    description: A JSON map of containers and their respective images to use
    required: false
  environment-vars:
    description: A JSON map of environment variables that will be replaced in the template (on all containers)
    required: false
  secrets:
    description: A JSON map of secrets variables that will be replaced in the template (on all containers)
    required: false
  wait-to-completion:
    description: Waits until the task is completed
    required: false

outputs:
  task-definition-arn:
    description: The registered Task Definition ARN

runs:
  using: node12
  main: index.js
